### ISSUE TITLE
Request for additional intra-team voice chat functionality

### ISSUE THREAD

**Issue by KirinekoPometo** [Centurion-Creative-Connect/System#83]
We request the addition of a radio system that can be used when joining a team.
It would be helpful to have the ability to have voice communication to each team from the administrator.
Please consider.

**Comment by DerpyNewbie** [comment]
Direct announcement from game administrators for in-team players is not I would like to implement for, because close-range mode megaphone is intended to be used in that situation.
If this was mainly meant for team communication tool, I'm up for it! I would like to see this feature used to communicate between distant teammates.

Anyway, I might need more specification to implement this. I'm guessing this feature is like PavlovVR or Onward like radio functionality. so maybe requirements are
- Interact around upper chest height to activate
- Maybe have a nice click-buzz SFX when activate/deactivate?
- Maybe show a indication on HUD while radio communication occurring with name of whose talking?

Let me know if I was understanding correctly, I'm looking forward for this feature!

**Comment by DerpyNewbie** [comment]
This might be an generic feature that can be used separately from Centurion System, considering to make a new repository for this. 🤔
Centurion System外でも使える/使いやすそうなギミックな気がしてきたので、別レポジトリに実装するか検討しています!

**Comment by DerpyNewbie** [comment]
[DerpyNewbie/VoiceComms](https://github.com/DerpyNewbie/VoiceComms) をリリースしました! これからCenturion Systemのプレイヤーチームと連携して動くものを実装しますね!

**Comment by DerpyNewbie** [comment]
[Centurion-Creative-Connect/System.VoiceCommsIntegration](https://github.com/Centurion-Creative-Connect/System.VoiceCommsIntegration) をリリースしました! 今後の無線周りでのリクエスト等は [Integration](https://github.com/Centurion-Creative-Connect/System.VoiceCommsIntegration) か [VoiceComms](https://github.com/derpynewbie/VoiceComms) にて受け付けます! よろしくお願いします!
